apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: python-producer
        image: rabii10/python_producer:v4.2.2
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-broker-service:19092"
        - name: TOPIC
          value: "demo"
        - name: MSG_RATE
          value: "100"
        - name: BURST_PROB
          value: "0.1" # Proba. des pics de MSG_RATE plus frequent
        - name: BURST_POWER
          value: "3" # valeur plus petit > des pics de MSG_RATE plus massives (min 1.1)
